eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://139.196.225.214:8081/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
logging:
  level:
    io:
      seata: info
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.gzf.account.entity
server:
  port: 8082
spring:
  application:
    name: account-server
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://116.62.136.225:3306/seata-account
    username: admin
